export const CALC_ACTIONS = {
  DIVIDE: "/",
  SUBSTRACT: "-",
  MULTIPLY: "*",
  ADD: "+",
  L_BRACKET: "(",
  R_BRACKET: ")",
  DOT: ".",
  CE: "CLEAR_WITH_HISTORY",
  C: "CLEAR",
  EQUAL: "CALC",
  ONE: "1",
  TWO: "2",
  THREE: "3",
  FOUR: "4",
  FIVE: "5",
  SIX: "6",
  SEVEN: "7",
  EIGHT: "8",
  NINE: "9",
  ZERO: "0",
}